#if defined FORMATS_INCLUDED
#endinput
#endif
#define FORMATS_INCLUDED

#define STR_RootPath "data/Speedrun Tas Tools"
#define STR_ReplayFolder "Replays"
#define STR_ReplayFolderForMultiplayers "Multiplayers"
#define STR_ZoneFolder "Zones"

#define STR_MessagePrefix "{vintage}[{dodgerblue}STR{vintage}]{ghostwhite} - "
#define STR_CSGOMessagePrefix "{olive}[{olive}STR{olive}]{default} - "
//#define STR_CSGOMessagePrefix "{lightblue}[{darkblue}STR{lightblue}]{default} - "

#define STR_CheckpointFormat "{ghostwhite}Checkpoint [{unique}%d{ghostwhite}] {lightblue}%s"
#define STR_CSGOCheckpointFormat "{default}Checkpoint [{orange}%d{default}] {bluegrey}%s"

#define STR_EndFinishFormat "{orchid}%s {ghostwhite}finished in {unique}%s"
#define STR_CSGOEndFinishFormat "{orchid}%s {default}finished in {orange}%s"

#define STR_ZoneSpeedEnterFormat "{ghostwhite}Zone enter velocity XY: {lightblue}%0.2f{ghostwhite} - Z: {lightblue}%0.2f"
#define STR_CSGOZoneSpeedEnterFormat "{default}Zone enter velocity XY: {bluegrey}%0.2f{default} - Z: {bluegrey}%0.2f"

#define STR_ZoneSpeedLeaveFormat "{ghostwhite}Zone leave velocity XY: {lightblue}%0.2f{ghostwhite} - Z: {lightblue}%0.2f"
#define STR_CSGOZoneSpeedLeaveFormat "{default}Zone leave velocity XY: {bluegrey}%0.2f{default} - Z: {bluegrey}%0.2f"
